temp <- tempfile()
download.file("https://archive.ics.uci.edu/ml/machine-learning-databases/00235/household_power_consumption.zip",temp)
data <- read.table(unz(temp, "household_power_consumption.txt"), sep=";",header = T)
unlink(temp)
data$Date1 <- as.Date(data$Date , format="%d/%m/%Y")
data<-subset(data,Date1 == "2007-02-01"|Date1 == "2007-02-02")
data$Global_active_power <- as.numeric(as.character(data$Global_active_power))
data$DateTime <- strptime(paste(data$Date, data$Time), "%d/%m/%Y %H:%M:%S")
png("plot2.png", width = 480, height = 480)
plot(data$DateTime,data$Global_active_power,type='l',ylab="Global Active Power (kilowatts)",xlab="")
dev.off()
