temp <- tempfile()
download.file("https://archive.ics.uci.edu/ml/machine-learning-databases/00235/household_power_consumption.zip",temp)
data <- read.table(unz(temp, "household_power_consumption.txt"), sep=";",header = T)
unlink(temp)
data$Date1 <- as.Date(data$Date , format="%d/%m/%Y")
data<-subset(data,Date1 == "2007-02-01"|Date1 == "2007-02-02")
data$Sub_metering_1 <- as.numeric(as.character(data$Sub_metering_1))
data$Sub_metering_2 <- as.numeric(as.character(data$Sub_metering_2))
data$Sub_metering_3 <- as.numeric(as.character(data$Sub_metering_3))
data$Global_active_power <- as.numeric(as.character(data$Global_active_power))
data$Voltage <- as.numeric(as.character(data$Voltage))
data$Global_reactive_power <- as.numeric(as.character(data$Global_reactive_power))
data$DateTime <- strptime(paste(data$Date, data$Time), "%d/%m/%Y %H:%M:%S")

png("plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))
plot(data$DateTime,data$Global_active_power,type='l',ylab="Global Active Power (kilowatts)",xlab="")
plot(data$DateTime,data$Voltage,type='l',ylab="Voltage",xlab="datetime")
plot(data$DateTime,data$Sub_metering_1,type='l',col="black",ylab="Energy sub metering",xlab="")
lines(data$DateTime,data$Sub_metering_2,col="red",type= "l" )
lines(data$DateTime,data$Sub_metering_3,col="blue",type= "l")
legend("topright",pch ="___", col = c("black", "red", "blue"),legend= c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(data$DateTime,data$Global_reactive_power,type='l',ylab="Global_reactive_power",xlab="datetime")
dev.off()